pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'Sonar'
    scannerMode: 'cli'
    cliScannerVersion: '7.2.0.5079'
    configMode: 'manual'
    cliProjectKey: 'Zotero'
    cliProjectName: 'Zotero'
    cliSources: '.'
    extraProperties: |
      sonar.inclusions=./app
      sonar.cfamily.build-wrapper-output=bw-output
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'